/**
 * Windows shortcut labels (Ctrl, not Cmd). Must match `dispatchEditorKey`.
 * Display only — do not invent new bindings here.
 */
export const CLIP_MENU_SHORTCUTS = {
  split: "S",
  cut: "Ctrl+X",
  copy: "Ctrl+C",
  paste: "Ctrl+V",
  duplicate: "Ctrl+D",
  delete: "Delete",
  rippleDelete: "Shift+Delete",
  liftRange: ";",
  extractRange: "'",
  closeGap: "G",
  rippleTrimInToPlayhead: "Q",
  rippleTrimOutToPlayhead: "Alt+W",
  selectAll: "Ctrl+A",
  selectAllOnTrack: "Ctrl+Shift+A",
} as const;

export const SHORTCUT_ROWS: { key: string; action: string }[] = [
  { key: "Space", action: "Play / Pause" },
  { key: "Tab / Shift+Tab", action: "Arrange / Cutter" },
  { key: "J / K / L", action: "Shuttle reverse / pause / forward" },
  { key: CLIP_MENU_SHORTCUTS.split, action: "Split at playhead (active/selected track(s))" },
  { key: "I", action: "Set IN" },
  { key: "O", action: "Set OUT" },
  { key: "Right-click ruler", action: "IN then OUT" },
  { key: "X", action: "Clear IN/OUT" },
  { key: "M", action: "Add marker" },
  { key: CLIP_MENU_SHORTCUTS.delete, action: "Lift-delete selected clip(s), VIS event, or marker" },
  { key: CLIP_MENU_SHORTCUTS.rippleDelete, action: "Ripple delete selected clip(s)" },
  { key: CLIP_MENU_SHORTCUTS.liftRange, action: "Lift range (IN/OUT)" },
  { key: CLIP_MENU_SHORTCUTS.extractRange, action: "Extract range (IN/OUT)" },
  { key: "Ctrl+click clip", action: "Toggle clip in selection" },
  { key: CLIP_MENU_SHORTCUTS.selectAll, action: "Select all clips (or all VIS events if a VIS event is focused)" },
  { key: CLIP_MENU_SHORTCUTS.selectAllOnTrack, action: "Select all clips on the primary clip’s track" },
  { key: ", / .", action: "Nudge clip ±1 frame" },
  { key: "Shift+, / Shift+.", action: "Nudge clip ±10 frames" },
  { key: "← / →", action: "Step playhead ±1 frame" },
  { key: "Home / End", action: "Playhead to project start / duration" },
  { key: "Shift+Home / Shift+End", action: "Playhead to IN / OUT (no-op if unset)" },
  { key: "↑ / ↓", action: "Previous / next edit point" },
  { key: CLIP_MENU_SHORTCUTS.closeGap, action: "Close gap under playhead (one track)" },
  { key: CLIP_MENU_SHORTCUTS.rippleTrimInToPlayhead, action: "Ripple trim in to playhead" },
  { key: CLIP_MENU_SHORTCUTS.rippleTrimOutToPlayhead, action: "Ripple trim out to playhead" },
  { key: "W", action: "Arm / disarm volume write (selected audio track; same as the W button)" },
  { key: "Ctrl+S", action: "Save project" },
  { key: "Ctrl+Shift+S", action: "Save project as" },
  { key: "Ctrl+Z", action: "Undo" },
  { key: "Ctrl+Y", action: "Redo" },
  { key: CLIP_MENU_SHORTCUTS.cut, action: "Cut selected clip(s)" },
  { key: CLIP_MENU_SHORTCUTS.copy, action: "Copy selected clip(s)" },
  { key: CLIP_MENU_SHORTCUTS.paste, action: "Paste clip(s) at playhead" },
  { key: CLIP_MENU_SHORTCUTS.duplicate, action: "Duplicate selection at playhead" },
  { key: "VIS event", action: "Move, stretch, Copy / Cut / Paste / Delete" },
  { key: "Ctrl+Shift+L", action: "Unlink A/V pair" },
  { key: "Inspector / clip menu", action: "Relink selected clip(s) to a new file" },
  { key: "Inspector checkbox / clip menu", action: "Lock / unlock clip (no key — L is shuttle, Ctrl+Shift+L unlinks)" },
  { key: "Lane / Mixer S", action: "Solo track (V/A lanes)" },
  { key: "Grp / group header", action: "Chapter group selected audio (collapse is UI-only, no group bus)" },
  { key: "Shift+edge-drag", action: "Ripple trim (same track)" },
  { key: "Abutting edge-drag", action: "Roll edit (shared cut)" },
  { key: "Alt+drag clip", action: "Slip source (clip or contiguous block)" },
  { key: "Alt+, / Alt+.", action: "Slip clip or block ±1 frame" },
  { key: "Ctrl+Alt+drag clip", action: "Slide clip or contiguous block (neighbors absorb)" },
  { key: "Shift+Alt+, / Shift+Alt+.", action: "Slide clip or block ±1 frame" },
  { key: "?", action: "Toggle this sheet" },
];
